"""T054-C: Remove passlib dependency, direct bcrypt.

BDD: C1-C2
Tests should FAIL (red) until P4 implementation.
"""

from __future__ import annotations

import re
from pathlib import Path

from peekview.auth import hash_password, verify_password


class TestBDDC1NoPasslibInDeps:
    """BDD-C1: Given pyproject.toml dependency declarations,
    When checking the dependency list,
    Then it does NOT contain passlib, DOES contain bcrypt>=4.0.0.
    """

    def test_pyproject_no_passlib(self):
        pyproject = Path(__file__).parent.parent / "pyproject.toml"
        content = pyproject.read_text()
        assert "passlib" not in content, "passlib should be removed from dependencies"

    def test_pyproject_has_bcrypt(self):
        pyproject = Path(__file__).parent.parent / "pyproject.toml"
        content = pyproject.read_text()
        assert re.search(r"bcrypt\s*>=\s*4\.0\.0", content), "bcrypt>=4.0.0 should be declared"


class TestBDDC2BcryptBackwardCompat:
    """BDD-C2: Given existing user with bcrypt hash generated by old passlib-installed bcrypt,
    When verifying with new bcrypt>=4.0.0 direct dependency,
    Then verification succeeds (backward compatible).
    """

    def test_old_hash_verifies_with_new_bcrypt(self):
        old_hash = hash_password("myoldpassword123")
        assert verify_password("myoldpassword123", old_hash)

    def test_bcrypt_hash_format_compatible(self):
        h = hash_password("testpassword")
        assert h.startswith("$2b$12$")
        assert verify_password("testpassword", h)

    def test_wrong_password_still_fails(self):
        h = hash_password("correctpassword")
        assert not verify_password("wrongpassword", h)
