#!/usr/bin/env python3
"""Cross-validation: Python fnv1a/prng vs Cap JS implementation.

Reads test vectors from /tmp/cap_test_vectors.json (generated by Node.js)
and verifies Python implementation produces identical outputs.

Run after: node scripts/verify_cap_algorithms.js
"""

import json
import sys
from pathlib import Path

HASH_OFFSET = 2166136261


def fnv1a(s: str) -> int:
    h = HASH_OFFSET
    for ch in s:
        h ^= ord(ch)
        h += (h << 1) + (h << 4) + (h << 7) + (h << 8) + (h << 24)
        h &= 0xFFFFFFFF
    return h


def fnv1a_resume(state: int, s: str) -> int:
    h = state
    for ch in s:
        h ^= ord(ch)
        h += (h << 1) + (h << 4) + (h << 7) + (h << 8) + (h << 24)
        h &= 0xFFFFFFFF
    return h


def prng_from_hash(initial_hash: int, length: int) -> str:
    state = initial_hash
    result = ""
    while len(result) < length:
        state ^= (state << 13) & 0xFFFFFFFF
        state ^= (state >> 17) & 0xFFFFFFFF
        state ^= (state << 5) & 0xFFFFFFFF
        state &= 0xFFFFFFFF
        result += format(state, "08x")
    return result[:length]


def main():
    vectors_file = Path("/tmp/cap_test_vectors.json")
    if not vectors_file.exists():
        print("ERROR: Test vectors not found. Run first:")
        print("  node scripts/verify_cap_algorithms.js")
        sys.exit(1)

    vectors = json.loads(vectors_file.read_text())
    mismatches = []

    for i, vec in enumerate(vectors):
        s = vec["str"]
        expected_hash = vec["hash"]
        expected_prng = vec["prng"]

        actual_hash = fnv1a(s)
        actual_prng = prng_from_hash(actual_hash, 32)

        if actual_hash != expected_hash:
            mismatches.append(f"[{i}] fnv1a('{s}'): JS={expected_hash}, PY={actual_hash}")
        elif actual_prng != expected_prng:
            mismatches.append(f"[{i}] prng('{s}'): JS={expected_prng}, PY={actual_prng}")

    print(f"Validated {len(vectors)} test vectors")
    print(f"  fnv1a('hello') = {fnv1a('hello')}")
    print(f"  prngFromHash(fnv1a('hello'), 32) = {prng_from_hash(fnv1a('hello'), 32)}")
    print()

    if mismatches:
        print(f"MISMATCHES: {len(mismatches)}")
        for m in mismatches[:10]:
            print(f"  {m}")
        if len(mismatches) > 10:
            print(f"  ... and {len(mismatches) - 10} more")
        sys.exit(1)
    else:
        print("ALL MATCHED - Python implementation is byte-for-byte compatible with Cap JS")
        sys.exit(0)


if __name__ == "__main__":
    main()
