apiVersion: v1
kind: Service
metadata:
  name: peekview-backend
  namespace: peekview
spec:
  type: ClusterIP
  selector:
    app: peekview
    component: backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
